# Generated by Django 5.2.6 on 2025-12-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('comp_ID', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('comp_name', models.CharField(max_length=100)),
                ('comp_address', models.CharField(max_length=100)),
                ('comp_about', models.TextField()),
                ('comp_type', models.CharField(choices=[('IT', 'IT'), ('Non It', 'NON IT'), ('mobile', 'Mobile company')], max_length=100)),
                ('comp_data', models.DateTimeField(auto_now=True)),
                ('comp_active', models.BooleanField(default=True)),
            ],
        ),
    ]
