# Generated by Django 5.2.6 on 2025-12-16 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_address', models.CharField(max_length=100)),
                ('emp_number', models.CharField(max_length=10)),
                ('emp_positon', models.CharField(max_length=50)),
                ('comp_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
    ]
