# Generated by Django 5.2.6 on 2025-10-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recp_name', models.CharField(verbose_name=100)),
                ('recp_dec', models.TextField()),
                ('recp_img', models.ImageField(upload_to='recp')),
            ],
        ),
    ]
