# Generated by Django 5.2.6 on 2025-12-12 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veg', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject_m',
            options={'ordering': ['student']},
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_no', models.IntegerField()),
                ('date_of_report', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_rank', to='veg.student')),
            ],
        ),
    ]
