# Generated by Django 5.2.6 on 2025-10-01 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recp',
            old_name='recp_dec',
            new_name='recp_decp',
        ),
    ]
