# Generated by Django 5.2.6 on 2025-10-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_car_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='L_Speed',
            field=models.IntegerField(default=0),
        ),
    ]
